[project]
name = "dev-deepagents-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepagents-cli>=0.0.10",
    "langchain-google-genai>=3.2.0",
]
